
import { GoogleGenAI, Type, Modality } from "@google/genai";

const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function transcribeAudio(base64Data: string, mimeType: string): Promise<string> {
  const ai = getAI();
  const audioPart = { inlineData: { data: base64Data, mimeType: mimeType } };
  const promptPart = {
    text: "You are an expert transcriptionist for the Ethiopian government. Transcribe the provided audio exactly as spoken. PERFORM SPEAKER DIARIZATION: Identify different speakers and label them as 'Speaker 1:', 'Speaker 2:', etc. If the language is Amharic, Oromo, Tigrinya, or English, provide the transcript in that language. Output ONLY the transcript with speaker labels."
  };

  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: { parts: [audioPart, promptPart] },
    config: { temperature: 0.1 }
  });
  return response.text || "No transcription available.";
}

export async function editImage(base64Image: string, mimeType: string, prompt: string): Promise<string> {
  const ai = getAI();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data: base64Image, mimeType } },
        { text: prompt }
      ]
    }
  });
  
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
  }
  throw new Error("No image generated by the model.");
}

export async function queryIntelligence(query: string, mode: 'search' | 'maps', location?: {lat: number, lng: number}) {
  const ai = getAI();
  const modelName = mode === 'search' ? 'gemini-3-flash-preview' : 'gemini-2.5-flash';
  const tools: any[] = mode === 'search' ? [{ googleSearch: {} }] : [{ googleMaps: {} }];
  
  const config: any = { tools };
  if (mode === 'maps' && location) {
    config.toolConfig = {
      retrievalConfig: {
        latLng: { latitude: location.lat, longitude: location.lng }
      }
    };
  }

  const response = await ai.models.generateContent({
    model: modelName,
    contents: query,
    config
  });

  return {
    text: response.text,
    grounding: response.candidates?.[0]?.groundingMetadata?.groundingChunks || []
  };
}

export async function generateVeoVideo(imageBytes: string, mimeType: string, prompt: string, aspectRatio: '16:9' | '9:16' = '16:9') {
  const ai = getAI();
  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt,
    image: { imageBytes, mimeType },
    config: { numberOfVideos: 1, resolution: '720p', aspectRatio }
  });

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 10000));
    operation = await ai.operations.getVideosOperation({ operation });
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  const res = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
  const blob = await res.blob();
  return URL.createObjectURL(blob);
}
