
import { jsPDF } from "jspdf";

export const exportToPdf = (text: string, filename: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Official Header
  doc.setFillColor(10, 61, 82); // Primary Brand Color
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("WAGHIMRA NATIONALITY ADMINISTRATION HIGH COURT", pageWidth / 2, 20, { align: "center" });
  doc.setFontSize(10);
  doc.text("FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA - AI JUDICIAL NODE", pageWidth / 2, 28, { align: "center" });
  
  // Body Content
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("OFFICIAL HEARING TRANSCRIPTION", 20, 55);
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Document ID: GH-${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 20, 62);
  doc.text(`Recorded Date: ${new Date().toLocaleDateString()}`, 20, 67);
  doc.text(`Generated by: 2S Tec Judicial Engine`, 20, 72);
  
  doc.setDrawColor(197, 160, 89); // Gold Secondary
  doc.setLineWidth(1);
  doc.line(20, 77, pageWidth - 20, 77);
  
  doc.setFontSize(11);
  const splitText = doc.splitTextToSize(text, pageWidth - 40);
  doc.text(splitText, 20, 87);
  
  // Footer / Signature
  const finalY = 87 + (splitText.length * 7);
  doc.setDrawColor(200, 200, 200);
  doc.line(pageWidth - 80, finalY + 30, pageWidth - 20, finalY + 30);
  doc.setFontSize(8);
  doc.text("Certified Court Clerk Signature", pageWidth - 80, finalY + 35);
  
  doc.save(`${filename}.pdf`);
};

export const exportToDoc = (text: string, filename: string) => {
  const header = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset='utf-8'><title>Transcription</title></head><body>
    <div style='font-family: "Segoe UI", Tahoma, sans-serif; padding: 40px;'>
      <div style='text-align: center; border-bottom: 2px solid #0a3d52; padding-bottom: 20px;'>
        <h2 style='color: #0a3d52; margin: 0;'>Waghimra Nationality Administration High Court</h2>
        <p style='color: #c5a059; font-weight: bold; margin: 5px 0;'>Federal Democratic Republic of Ethiopia</p>
      </div>
      <div style='margin-top: 30px;'>
        <p style='color: #666; font-size: 11px;'>Generated via 2S Tec Judicial Node on ${new Date().toLocaleString()}</p>
        <h3 style='color: #333;'>Official Hearing Transcript</h3>
        <div style='white-space: pre-wrap; font-size: 12pt; line-height: 1.6;'>${text}</div>
      </div>
      <div style='margin-top: 100px; text-align: right;'>
        <div style='width: 200px; border-top: 1px solid #000; display: inline-block;'></div>
        <p style='font-size: 10px;'>Official Seal & Clerk Signature</p>
      </div>
    </div>
    </body></html>`;

  const blob = new Blob(['\ufeff', header], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
